# Generated by Django 4.1.7 on 2023-03-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_alter_titles_title_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
